# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        
      - uses: actions/checkout@v2
        with:
              repository: 'hexojs/hexo-theme-unit-test'
              
      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
    # Set always-auth in npmrc
              
      - name:  Make dirs for themes
        run: mkdir themes
      # Runs a set of commands using the runners shell
      - name: Clone Kratos-Rebirth into themes dir
        run:  git clone --single-branch --branch master https://github.com/${GITHUB_REPOSITORY} ./themes/kratos-rebirth
      - name: Edit Hexo site settings
        run: |
           sed -i "s/title: Hexo/title: Kratos-Rebirth/" "_config.yml"
           sed -i "s/subtitle:/subtitle: A demo site of theme Kratos Rebirth/" "_config.yml"
           sed -i "s/description:/description: A demo site of theme Kratos Rebirth/" "_config.yml"
           sed -i "s/author: John Doe/author: Candinya/" "_config.yml"
           sed -i "s/language:/language: zh-CN/" "_config.yml"
           sed -i "s|url: http://yoursite.com|url: https://${SITE_URL}|" "_config.yml"
           sed -i "s|permalink: :year/:month/:day/:title/|permalink: posts/:title/|" "_config.yml"
           sed -i "s/theme: landscape/theme: kratos-rebirth/" "_config.yml"
